Главная страница на гридах
htmlacademy-htmlcss/1531661-sedona-29 pull request #6
Opened 2020-09-22 12:49 UTC by j7amo

Расположил элементы на главной странице по сетке.

А именно:

- хедер (главная навигация) - грид

- причины крутизны - грид

- форма запроса отелей - грид

- футер - грид

+ по мелочи там где-то ещё могут быть грид

2020-09-22 18:16 UTC, CCher requested changes
Отлично поработали! С гридами вижу разобрались, да и с флексами скорее всего тоже. Это замечательно.
Предлагаю поправить логотип и всё будет на 5 баллов :)

2020-09-22 18:16 UTC, CCher commented on css/style.css
> +  left: 46.3%;
в принципе, это нормальное решение (хоть и не в канве прошедшей лекции), только немного "не докрутили". Суть в чём. Элемент позиционируется относительно экрана и вне потока. И он должен стоять по центру и прижатым кверху экрана. Вроде бы взять и задать координаты как top:0; left:50%; 
Но он встаёт не точно по центру! Это Вы подметили и задали высчитанное 46,3%. Да, для одной ширины экрана (для который Вы считали ) это сработает, но измените ширину экрана и логотип из центра уйдёт. Значит нужна позиция 50%. И вспоминаем, что отсчёт координат идёт от ЛЕВОГО верхнего угла элемента и элемент имеет свою ширину! Значит, чтобы центр был по центру нужно задать элементу отрицательный марджин влево на половину ширины блока: margin-left: -69px;
И не забыть, что абсолют позиционируется относительно родителя, а родитель в данном случае main-navigation, которому нужно задать position:relative; И тогда эта схема будет чётко работать.

Ну а можно сделать как в демке Барбершопа из лекции - поставить на nav грид контейнер и тогда будет соответствовать изучаемому материалу и закрепите на практике навык по гридам.

2020-09-23 11:45 UTC, j7amo reviewed
Теперь раскладка в целом на гридах. Обошёлся без position: absolute. Также посмотрел вёрстку в Pixel Perfect, покрутил стили и теперь она приближена (+- 5px) к макету.

2020-09-23 12:06 UTC, CCher approved these changes

2020-09-23 12:06 UTC, merged